const fs = require('fs');
const path = require('path');
const filePath = path.resolve('v3/js/chatbot.js');
let content = fs.readFileSync(filePath, 'utf8');

const batch2 = [
    // ═══ CIENCIA (50) ═══
    { q: "¿Cuántos planetas tiene el sistema solar?", a: "8 planetas: Mercurio, Venus, Tierra, Marte, Júpiter, Saturno, Urano y Neptuno." },
    { q: "¿A qué temperatura hierve el agua?", a: "A 100°C a nivel del mar." },
    { q: "¿A qué temperatura se congela el agua?", a: "A 0°C en condiciones normales." },
    { q: "¿Cuánto tarda la Tierra en girar alrededor del Sol?", a: "Aproximadamente 365,25 días." },
    { q: "¿Qué es el ADN?", a: "El ADN (ácido desoxirribonucleico) contiene la información genética de los seres vivos." },
    { q: "¿Qué es la fotosíntesis?", a: "Proceso por el cual las plantas convierten luz solar, agua y CO₂ en oxígeno y glucosa." },
    { q: "¿Cuántos huesos tiene el cuerpo humano?", a: "Un adulto tiene 206 huesos." },
    { q: "¿Cuál es la velocidad de la luz?", a: "Aproximadamente 299.792 km/s en el vacío." },
    { q: "¿Qué es la gravedad?", a: "Fuerza de atracción entre cuerpos con masa. En la Tierra, 9,8 m/s²." },
    { q: "¿Qué es un átomo?", a: "La unidad básica de la materia, compuesta por protones, neutrones y electrones." },
    { q: "¿Qué es una molécula?", a: "Un grupo de átomos unidos químicamente. El agua (H₂O) es una molécula de 2 hidrógenos y 1 oxígeno." },
    { q: "¿Cuál es el elemento más abundante del universo?", a: "El hidrógeno, que compone aproximadamente el 75% de la materia visible del universo." },
    { q: "¿Qué es la tabla periódica?", a: "Una tabla que organiza todos los elementos químicos conocidos por su número atómico, propiedades y estructura electrónica." },
    { q: "¿Cuántos elementos hay en la tabla periódica?", a: "Actualmente hay 118 elementos confirmados en la tabla periódica." },
    { q: "¿Qué es el oxígeno?", a: "Un elemento químico esencial para la respiración. Compone el 21% de la atmósfera terrestre." },
    { q: "¿Qué causa los terremotos?", a: "Los terremotos son causados por el movimiento de las placas tectónicas de la corteza terrestre." },
    { q: "¿Qué es un volcán?", a: "Una abertura en la corteza terrestre por donde sale magma, gases y cenizas del interior de la Tierra." },
    { q: "¿Qué es el efecto invernadero?", a: "Un fenómeno natural donde ciertos gases atmosféricos retienen calor del sol, manteniendo la temperatura terrestre habitable." },
    { q: "¿Qué es el cambio climático?", a: "El cambio en los patrones climáticos globales, principalmente causado por el aumento de gases de efecto invernadero." },
    { q: "¿Qué es una célula?", a: "La unidad básica de la vida. Todos los seres vivos están compuestos por células." },
    { q: "¿Cuántas células tiene el cuerpo humano?", a: "Aproximadamente 37 billones de células." },
    { q: "¿Qué es la evolución?", a: "El proceso de cambio en las especies a lo largo del tiempo mediante selección natural, propuesto por Charles Darwin." },
    { q: "¿Quién fue Charles Darwin?", a: "Naturalista inglés que formuló la teoría de la evolución por selección natural en su obra 'El origen de las especies' (1859)." },
    { q: "¿Qué es un agujero negro?", a: "Una región del espacio con gravedad tan intensa que nada, ni siquiera la luz, puede escapar." },
    { q: "¿Qué es la Vía Láctea?", a: "Nuestra galaxia, que contiene entre 100.000 y 400.000 millones de estrellas, incluyendo nuestro Sol." },
    { q: "¿Cuántas estrellas tiene el universo?", a: "Se estima que hay más de 200.000 trillones de estrellas en el universo observable." },
    { q: "¿Qué es un año luz?", a: "La distancia que recorre la luz en un año: aproximadamente 9,46 billones de kilómetros." },
    { q: "¿Cuál es la estrella más cercana al Sol?", a: "Próxima Centauri, a unos 4,24 años luz de distancia." },
    { q: "¿Qué es la capa de ozono?", a: "Una capa de gas ozono (O₃) en la estratosfera que protege la Tierra de los rayos ultravioleta del Sol." },
    { q: "¿Cómo funciona una vacuna?", a: "Estimula el sistema inmunológico para que produzca anticuerpos contra un patógeno específico sin causar la enfermedad." },
    { q: "¿Qué es un virus?", a: "Un agente infeccioso microscópico que necesita una célula huésped para replicarse." },
    { q: "¿Qué es una bacteria?", a: "Un microorganismo unicelular procariota que puede ser beneficioso o patógeno." },
    { q: "¿Cuánta agua tiene el cuerpo humano?", a: "Aproximadamente el 60% del cuerpo humano adulto es agua." },
    { q: "¿Cuál es el órgano más grande del cuerpo?", a: "La piel es el órgano más grande del cuerpo humano." },
    { q: "¿Cuánto pesa el cerebro humano?", a: "Aproximadamente 1,4 kilogramos en un adulto." },
    { q: "¿Qué es el Big Bang?", a: "La teoría científica que explica el origen del universo hace unos 13.800 millones de años." },
    { q: "¿Cuántos años tiene la Tierra?", a: "Aproximadamente 4.540 millones de años." },
    { q: "¿Qué es la energía solar?", a: "Energía obtenida a partir de la radiación del Sol, utilizada para generar electricidad o calor." },
    { q: "¿Qué es la energía nuclear?", a: "Energía liberada por reacciones nucleares (fisión o fusión) en los átomos." },
    { q: "¿Qué son los dinosaurios?", a: "Reptiles que dominaron la Tierra durante unos 165 millones de años, hasta su extinción hace 66 millones de años." },
    { q: "¿Por qué se extinguieron los dinosaurios?", a: "La teoría más aceptada es el impacto de un asteroide en Chicxulub, México, hace 66 millones de años." },
    { q: "¿Qué es la fotoeléctrica?", a: "El efecto fotoeléctrico es la emisión de electrones cuando la luz incide sobre un material. Einstein lo explicó en 1905." },
    { q: "¿Qué es la relatividad?", a: "La teoría de la relatividad de Einstein describe cómo el espacio y el tiempo se curvan en presencia de masa y energía." },
    { q: "¿Qué es un láser?", a: "Light Amplification by Stimulated Emission of Radiation: un dispositivo que emite luz coherente y concentrada." },
    { q: "¿Qué es la temperatura absoluta?", a: "El cero absoluto es -273,15°C (0 Kelvin), la temperatura más baja teóricamente posible." },
    { q: "¿Cuántos sentidos tiene el ser humano?", a: "Tradicionalmente 5: vista, oído, olfato, gusto y tacto. La ciencia moderna reconoce otros como el equilibrio y la propiocepción." },
    { q: "¿Cuánta sangre tiene el cuerpo humano?", a: "Un adulto tiene aproximadamente 5 litros de sangre." },
    { q: "¿Cuántas neuronas tiene el cerebro?", a: "Aproximadamente 86.000 millones de neuronas." },
    { q: "¿Qué es el pH?", a: "Una escala de 0 a 14 que mide la acidez o alcalinidad de una solución. 7 es neutro." },
    { q: "¿Qué son los cromosomas?", a: "Estructuras dentro de las células que contienen el ADN. Los humanos tienen 46 cromosomas (23 pares)." },

    // ═══ CULTURA GENERAL (50) ═══
    { q: "¿Cuántos días tiene un año?", a: "365, o 366 en años bisiestos." },
    { q: "¿Cuántas horas tiene un día?", a: "24 horas." },
    { q: "¿Cuántos minutos tiene una hora?", a: "60 minutos." },
    { q: "¿Cuántos segundos tiene un minuto?", a: "60 segundos." },
    { q: "¿Cuántos meses tiene un año?", a: "12 meses." },
    { q: "¿Cuántos días tiene una semana?", a: "7 días." },
    { q: "¿Cuántas letras tiene el abecedario?", a: "El abecedario español tiene 27 letras." },
    { q: "¿Qué hora es?", a: "No tengo acceso a la hora en tiempo real. ¿Hay algo de OpenCORE en lo que pueda ayudarte?" },
    { q: "¿Qué día es hoy?", a: "No tengo acceso al calendario, pero estoy disponible cualquier día para resolver tus dudas tecnológicas." },
    { q: "¿Qué es una UF?", a: "La UF (Unidad de Fomento) es una unidad de cuenta chilena reajustable según la inflación." },
    { q: "¿Cuánto vale una UF?", a: "Fluctúa diariamente. Consulta sii.cl o el Banco Central. Suele estar entre 35.000 y 40.000 CLP." },
    { q: "¿Cuántas notas musicales hay?", a: "Hay 7 notas musicales: Do, Re, Mi, Fa, Sol, La, Si." },
    { q: "¿Cuántos colores tiene el arcoíris?", a: "7 colores: rojo, naranja, amarillo, verde, azul, índigo y violeta." },
    { q: "¿Cuántos signos del zodiaco hay?", a: "12 signos: Aries, Tauro, Géminis, Cáncer, Leo, Virgo, Libra, Escorpio, Sagitario, Capricornio, Acuario, Piscis." },
    { q: "¿Cuántas maravillas del mundo antiguo hay?", a: "7 Maravillas del Mundo Antiguo. De ellas, solo la Pirámide de Guiza sigue en pie." },
    { q: "¿Cuál es el idioma más hablado del mundo?", a: "El chino mandarín por hablantes nativos. El inglés es el más hablado incluyendo no nativos." },
    { q: "¿Cuántos idiomas hay en el mundo?", a: "Aproximadamente 7.000 idiomas activos en el mundo." },
    { q: "¿Cuándo es Navidad?", a: "El 25 de diciembre." },
    { q: "¿Cuándo es Año Nuevo?", a: "El 1 de enero." },
    { q: "¿Qué significa CEO?", a: "Chief Executive Officer, el Director Ejecutivo de una empresa." },
    { q: "¿Qué significa CTO?", a: "Chief Technology Officer, el Director de Tecnología de una empresa." },
    { q: "¿Qué significa WiFi?", a: "Es una marca comercial para redes inalámbricas. No es un acrónimo formal, aunque se asocia con 'Wireless Fidelity'." },
    { q: "¿Cuántos jugadores tiene un equipo de fútbol?", a: "11 jugadores en cancha, incluyendo el portero." },
    { q: "¿Cuánto mide un campo de fútbol?", a: "Entre 100-110 metros de largo y 64-75 metros de ancho (FIFA)." },
    { q: "¿Quién pintó la Mona Lisa?", a: "Leonardo da Vinci, entre 1503 y 1519. Está en el Museo del Louvre en París." },
    { q: "¿Quién escribió Don Quijote?", a: "Miguel de Cervantes Saavedra, publicado en 1605 y 1615." },
    { q: "¿Cuántos países hay en el mundo?", a: "193 países miembros de la ONU, más 2 estados observadores." },
    { q: "¿Cuál es el deporte más popular del mundo?", a: "El fútbol (soccer), con más de 4.000 millones de seguidores." },
    { q: "¿Cuál es la película más taquillera de la historia?", a: "Avatar (2009) de James Cameron, con más de 2.900 millones de dólares." },
    { q: "¿Cuál es la red social más usada?", a: "Facebook, con más de 3.000 millones de usuarios activos." },
    { q: "¿Qué es un emoji?", a: "Un pictograma o ideograma digital usado en comunicaciones electrónicas para expresar emociones, conceptos u objetos." },
    { q: "¿Cuánto dura un partido de fútbol?", a: "90 minutos divididos en dos tiempos de 45 minutos, más tiempo añadido." },
    { q: "¿Cuántas teclas tiene un piano?", a: "Un piano estándar tiene 88 teclas: 52 blancas y 36 negras." },
    { q: "¿Cuántas cuerdas tiene una guitarra?", a: "Una guitarra estándar tiene 6 cuerdas." },
    { q: "¿Quién es el futbolista más famoso?", a: "Históricamente, Pelé y Maradona. En la era moderna, Lionel Messi y Cristiano Ronaldo." },
    { q: "¿Cuándo se inventó la televisión?", a: "Las primeras demostraciones fueron en la década de 1920. Philo Farnsworth y John Logie Baird fueron pioneros." },
    { q: "¿Qué es Wikipedia?", a: "Una enciclopedia libre y colaborativa en línea, fundada en 2001." },
    { q: "¿Qué es un podcast?", a: "Un programa de audio digital descargable o en streaming, generalmente organizado en episodios temáticos." },
    { q: "¿Cuántos dientes tiene un adulto?", a: "Un adulto tiene 32 dientes, incluyendo las muelas del juicio." },
    { q: "¿Cuánto mide un maratón?", a: "Un maratón mide 42,195 kilómetros." },

    // ═══ TECNOLOGÍA (50) ═══
    { q: "¿Qué es una API?", a: "Una API (Application Programming Interface) permite que dos aplicaciones se comuniquen entre sí." },
    { q: "¿Qué es la nube?", a: "Cloud computing: acceso a servicios de computación a través de internet sin infraestructura propia." },
    { q: "¿Qué es un servidor?", a: "Un computador que proporciona servicios, datos o recursos a otros computadores." },
    { q: "¿Qué es una base de datos?", a: "Un sistema para almacenar, gestionar y recuperar información. Puede ser SQL o NoSQL." },
    { q: "¿Qué es un ERP?", a: "Enterprise Resource Planning: sistema que integra finanzas, inventario, producción y RRHH." },
    { q: "¿Qué es un CRM?", a: "Customer Relationship Management: sistema para gestionar relaciones con clientes." },
    { q: "¿Qué es un SLA?", a: "Service Level Agreement: acuerdo que define estándares de calidad y tiempos de respuesta." },
    { q: "¿Qué es machine learning?", a: "Rama de la IA donde los sistemas aprenden de datos para mejorar sin ser programados explícitamente." },
    { q: "¿Qué es un algoritmo?", a: "Secuencia de pasos lógicos para resolver un problema. Base de toda la programación." },
    { q: "¿Qué es Python?", a: "Lenguaje de programación popular por su simplicidad. Usado en ciencia de datos, IA y automatización." },
    { q: "¿Qué es JavaScript?", a: "El lenguaje más usado en la web. Permite crear páginas interactivas." },
    { q: "¿Qué es HTML?", a: "HyperText Markup Language: lenguaje para crear la estructura de páginas web." },
    { q: "¿Qué es CSS?", a: "Cascading Style Sheets: lenguaje que define el diseño visual de las páginas web." },
    { q: "¿Qué es Linux?", a: "Sistema operativo de código abierto, muy usado en servidores por su estabilidad y seguridad." },
    { q: "¿Qué es GitHub?", a: "Plataforma de desarrollo colaborativo con control de versiones Git." },
    { q: "¿Qué es Docker?", a: "Una plataforma de contenedores que permite empaquetar aplicaciones con todas sus dependencias." },
    { q: "¿Qué es Kubernetes?", a: "Un sistema de orquestación de contenedores creado por Google para automatizar despliegues." },
    { q: "¿Qué es SQL?", a: "Structured Query Language: lenguaje para gestionar y consultar bases de datos relacionales." },
    { q: "¿Qué es NoSQL?", a: "Bases de datos no relacionales diseñadas para datos no estructurados, escalabilidad y flexibilidad." },
    { q: "¿Qué es un firewall?", a: "Un sistema de seguridad que controla el tráfico de red, bloqueando accesos no autorizados." },
    { q: "¿Qué es la ciberseguridad?", a: "La práctica de proteger sistemas, redes y datos contra ataques digitales." },
    { q: "¿Qué es el phishing?", a: "Un fraude digital donde se suplanta la identidad de una entidad para robar datos personales." },
    { q: "¿Qué es blockchain?", a: "Tecnología de registro distribuido e inmutable, base de las criptomonedas." },
    { q: "¿Qué es Bitcoin?", a: "La primera criptomoneda descentralizada, creada por Satoshi Nakamoto en 2009." },
    { q: "¿Qué es el IoT?", a: "Internet of Things: la interconexión de dispositivos físicos a internet." },
    { q: "¿Qué es SaaS?", a: "Software as a Service: software distribuido como servicio a través de internet." },
    { q: "¿Qué es IaaS?", a: "Infrastructure as a Service: infraestructura de computación como servicio en la nube." },
    { q: "¿Qué es PaaS?", a: "Platform as a Service: plataforma de desarrollo en la nube." },
    { q: "¿Qué es AWS?", a: "Amazon Web Services: la plataforma de servicios en la nube más grande del mundo." },
    { q: "¿Qué es Azure?", a: "Microsoft Azure: plataforma de servicios en la nube de Microsoft." },
    { q: "¿Qué es Google Cloud?", a: "Google Cloud Platform (GCP): la plataforma de servicios en la nube de Google." },
    { q: "¿Qué es un dominio web?", a: "El nombre único que identifica un sitio web en internet, como opencore.cl." },
    { q: "¿Qué es el hosting?", a: "Servicio que almacena los archivos de un sitio web en un servidor accesible por internet." },
    { q: "¿Qué es SSL?", a: "Secure Sockets Layer: protocolo de seguridad para cifrar comunicaciones en internet (HTTPS)." },
    { q: "¿Qué es un backup?", a: "Una copia de seguridad de datos para poder restaurarlos en caso de pérdida." },
    { q: "¿Qué es un bug?", a: "Un error en el código de software que causa comportamiento inesperado." },
    { q: "¿Qué es debugging?", a: "El proceso de identificar y corregir errores (bugs) en el código." },
    { q: "¿Qué es frontend?", a: "La parte visual de una aplicación: lo que el usuario ve e interactúa." },
    { q: "¿Qué es backend?", a: "La parte del servidor de una aplicación: lógica, base de datos y procesamiento." },
    { q: "¿Qué es full stack?", a: "Un desarrollador que trabaja tanto en frontend como en backend." },
    { q: "¿Qué es responsive design?", a: "Diseño web que se adapta automáticamente a distintos tamaños de pantalla." },
    { q: "¿Qué es TypeScript?", a: "Un superset de JavaScript que añade tipado estático, creado por Microsoft." },
    { q: "¿Qué es React?", a: "Una biblioteca JavaScript creada por Meta (Facebook) para construir interfaces de usuario." },
    { q: "¿Qué es Node.js?", a: "Un entorno de ejecución que permite usar JavaScript en el servidor." },
    { q: "¿Qué es REST?", a: "Representational State Transfer: un estilo de arquitectura para APIs web." },
    { q: "¿Qué es GraphQL?", a: "Un lenguaje de consultas para APIs creado por Facebook, alternativa a REST." },
    { q: "¿Qué es microservicios?", a: "Arquitectura donde una aplicación se divide en servicios independientes y pequeños." },
    { q: "¿Qué es CI/CD?", a: "Integración Continua / Despliegue Continuo: prácticas de automatización en desarrollo de software." },
    { q: "¿Qué es Agile?", a: "Metodología de desarrollo de software basada en iteraciones cortas, colaboración y adaptabilidad." },
    { q: "¿Qué es un sprint?", a: "Un período de tiempo fijo (generalmente 2 semanas) en Scrum donde se completa un conjunto de trabajo." }
];

const qnaStr = batch2.map(q =>
    '  { q: ' + JSON.stringify(q.q) + ', a: ' + JSON.stringify(q.a) + ' }'
).join(',\n');

const closingPattern = '\n];\n';
const lastClose = content.lastIndexOf(closingPattern);
const before = content.substring(0, lastClose);
const after = content.substring(lastClose);

const injected = before + ',\n\n  // ══════════════════════════════════════════════\n  // CIENCIA (50) + CULTURA GENERAL (50) + TECNOLOGÍA (50)\n  // ══════════════════════════════════════════════\n' + qnaStr + after;

fs.writeFileSync(filePath, injected, 'utf8');
const final = fs.readFileSync(filePath, 'utf8');
const count = (final.match(/\{ q: /g) || []).length;
console.log('✅ Batch 2 done: ' + count + ' Q&As | +' + batch2.length + ' added');
