const fs = require('fs');
const path = require('path');
const filePath = path.resolve('v3/js/chatbot.js');
let content = fs.readFileSync(filePath, 'utf8');

const batch1 = [
    // ═══ MATEMÁTICAS (50) ═══
    { q: "¿Cuánto es 2+2?", a: "2 + 2 = 4. Si necesitas calcular el ROI de un proyecto tecnológico, eso sí se pone interesante." },
    { q: "¿Cuánto es 3+3?", a: "3 + 3 = 6." },
    { q: "¿Cuánto es 5+5?", a: "5 + 5 = 10." },
    { q: "¿Cuánto es 10+10?", a: "10 + 10 = 20." },
    { q: "¿Cuánto es 7x8?", a: "7 × 8 = 56." },
    { q: "¿Cuánto es 100÷4?", a: "100 ÷ 4 = 25." },
    { q: "¿Cuánto es la raíz cuadrada de 144?", a: "La raíz cuadrada de 144 es 12." },
    { q: "¿Cuánto es 15% de 200?", a: "El 15% de 200 es 30." },
    { q: "¿Cuánto es un millón dividido en mil?", a: "1.000.000 ÷ 1.000 = 1.000." },
    { q: "¿Cuántos metros tiene un kilómetro?", a: "Un kilómetro tiene 1.000 metros." },
    { q: "¿Cuánto es 9x9?", a: "9 × 9 = 81." },
    { q: "¿Cuánto es 12x12?", a: "12 × 12 = 144." },
    { q: "¿Cuánto es 25+75?", a: "25 + 75 = 100." },
    { q: "¿Cuánto es 1000-350?", a: "1.000 - 350 = 650." },
    { q: "¿Cuánto es 50% de 400?", a: "El 50% de 400 es 200." },
    { q: "¿Cuánto es 20% de 1000?", a: "El 20% de 1.000 es 200." },
    { q: "¿Cuánto es la raíz cuadrada de 225?", a: "La raíz cuadrada de 225 es 15." },
    { q: "¿Cuánto es 6x7?", a: "6 × 7 = 42. Curiosamente, también es la respuesta a la vida, según Douglas Adams." },
    { q: "¿Cuánto es 8x9?", a: "8 × 9 = 72." },
    { q: "¿Cuánto es 15x15?", a: "15 × 15 = 225." },
    { q: "¿Cuánto es 1+1?", a: "1 + 1 = 2. Notable." },
    { q: "¿Cuánto es 100x100?", a: "100 × 100 = 10.000." },
    { q: "¿Cuánto es 500÷5?", a: "500 ÷ 5 = 100." },
    { q: "¿Cuánto es 3 al cubo?", a: "3³ = 27." },
    { q: "¿Cuánto es 2 elevado a 10?", a: "2¹⁰ = 1.024. Exactamente 1 KB en informática." },
    { q: "¿Cuánto es 10% de 500?", a: "El 10% de 500 es 50." },
    { q: "¿Cuántos centímetros tiene un metro?", a: "Un metro tiene 100 centímetros." },
    { q: "¿Cuántos gramos tiene un kilogramo?", a: "Un kilogramo tiene 1.000 gramos." },
    { q: "¿Cuántos mililitros tiene un litro?", a: "Un litro tiene 1.000 mililitros." },
    { q: "¿Cuál es el número Pi?", a: "Pi (π) es aproximadamente 3,14159. Es la relación entre la circunferencia y el diámetro de un círculo." },
    { q: "¿Qué es un número primo?", a: "Un número primo es aquel que solo es divisible por 1 y por sí mismo. Ejemplos: 2, 3, 5, 7, 11, 13." },
    { q: "¿Cuánto es un billón?", a: "Depende del sistema. En el sistema español, un billón es un millón de millones (10¹²). En el sistema americano, es mil millones (10⁹)." },
    { q: "¿Qué es el teorema de Pitágoras?", a: "En un triángulo rectángulo, el cuadrado de la hipotenusa es igual a la suma de los cuadrados de los catetos: a² + b² = c²." },
    { q: "¿Cuánto es 0÷0?", a: "0 ÷ 0 es una indeterminación matemática. No tiene un valor definido." },
    { q: "¿Todo número multiplicado por cero da cero?", a: "Sí. Cualquier número multiplicado por cero siempre da cero." },
    { q: "¿Cuánto es 11x11?", a: "11 × 11 = 121." },
    { q: "¿Cuánto es 13x13?", a: "13 × 13 = 169." },
    { q: "¿Cuántos bytes tiene un kilobyte?", a: "Técnicamente, 1 KB = 1.024 bytes (en base binaria) o 1.000 bytes (en base decimal SI)." },
    { q: "¿Cuántos kilobytes tiene un megabyte?", a: "1 MB = 1.024 KB (binario) o 1.000 KB (decimal)." },
    { q: "¿Cuánto es la raíz cuadrada de 100?", a: "La raíz cuadrada de 100 es 10." },
    { q: "¿Cuánto es 4 elevado a 3?", a: "4³ = 64." },
    { q: "¿Cuánto es 5 factorial?", a: "5! = 5 × 4 × 3 × 2 × 1 = 120." },
    { q: "¿Cuánto es 10 factorial?", a: "10! = 3.628.800." },
    { q: "¿Qué es un porcentaje?", a: "Un porcentaje es una proporción expresada como una fracción de 100. Por ejemplo, 25% significa 25 de cada 100." },
    { q: "¿Cuánto es 200÷8?", a: "200 ÷ 8 = 25." },
    { q: "¿Cuánto es 33+67?", a: "33 + 67 = 100." },
    { q: "¿Cuánto es 999+1?", a: "999 + 1 = 1.000." },
    { q: "¿Cuánto es la mitad de 50?", a: "La mitad de 50 es 25." },
    { q: "¿Cuánto es el doble de 125?", a: "El doble de 125 es 250." },
    { q: "¿Cuánto es el triple de 33?", a: "El triple de 33 es 99." },

    // ═══ GEOGRAFÍA (50) ═══
    { q: "¿Cuál es la capital de Chile?", a: "La capital de Chile es Santiago." },
    { q: "¿Cuál es la capital de Argentina?", a: "La capital de Argentina es Buenos Aires." },
    { q: "¿Cuál es la capital de Francia?", a: "La capital de Francia es París." },
    { q: "¿Cuál es la capital de Japón?", a: "La capital de Japón es Tokio." },
    { q: "¿Cuál es la capital de Estados Unidos?", a: "La capital de Estados Unidos es Washington D.C." },
    { q: "¿Cuál es la capital de Brasil?", a: "La capital de Brasil es Brasilia." },
    { q: "¿Cuál es la capital de México?", a: "La capital de México es Ciudad de México." },
    { q: "¿Cuál es la capital de Perú?", a: "La capital de Perú es Lima." },
    { q: "¿Cuál es la capital de Colombia?", a: "La capital de Colombia es Bogotá." },
    { q: "¿Cuál es la capital de España?", a: "La capital de España es Madrid." },
    { q: "¿Cuál es la capital de Italia?", a: "La capital de Italia es Roma." },
    { q: "¿Cuál es la capital de Alemania?", a: "La capital de Alemania es Berlín." },
    { q: "¿Cuál es la capital de Reino Unido?", a: "La capital del Reino Unido es Londres." },
    { q: "¿Cuál es la capital de Canadá?", a: "La capital de Canadá es Ottawa." },
    { q: "¿Cuál es la capital de Australia?", a: "La capital de Australia es Canberra, no Sídney como muchos creen." },
    { q: "¿Cuál es la capital de China?", a: "La capital de China es Pekín (Beijing)." },
    { q: "¿Cuál es la capital de Rusia?", a: "La capital de Rusia es Moscú." },
    { q: "¿Cuál es la capital de India?", a: "La capital de India es Nueva Delhi." },
    { q: "¿Cuál es la capital de Egipto?", a: "La capital de Egipto es El Cairo." },
    { q: "¿Cuál es la capital de Sudáfrica?", a: "Sudáfrica tiene tres capitales: Pretoria (administrativa), Ciudad del Cabo (legislativa) y Bloemfontein (judicial)." },
    { q: "¿Cuál es el país más grande del mundo?", a: "Rusia es el país más grande del mundo por superficie, con más de 17 millones de km²." },
    { q: "¿Cuál es el río más largo del mundo?", a: "El río más largo del mundo es el Amazonas, con aproximadamente 7.062 km." },
    { q: "¿Cuál es la montaña más alta del mundo?", a: "El Monte Everest, con 8.849 metros sobre el nivel del mar." },
    { q: "¿Cuántos continentes hay?", a: "Hay 7 continentes: América, Europa, Asia, África, Oceanía, Antártida." },
    { q: "¿Cuántos océanos hay?", a: "Hay 5 océanos: Pacífico, Atlántico, Índico, Ártico y Antártico." },
    { q: "¿Cuál es el océano más grande?", a: "El Océano Pacífico es el más grande, cubriendo más de 165 millones de km²." },
    { q: "¿Cuál es el país más pequeño del mundo?", a: "La Ciudad del Vaticano, con solo 0,44 km²." },
    { q: "¿Cuál es el lago más grande del mundo?", a: "El Mar Caspio, aunque técnicamente es un lago, es el más grande con 371.000 km²." },
    { q: "¿Cuál es la isla más grande del mundo?", a: "Groenlandia, con aproximadamente 2,16 millones de km²." },
    { q: "¿Cuál es el desierto más grande del mundo?", a: "El desierto más grande es la Antártida (desierto frío). El desierto cálido más grande es el Sahara." },
    { q: "¿Cuál es la capital de Bolivia?", a: "La capital constitucional es Sucre, pero la sede de gobierno es La Paz." },
    { q: "¿Cuál es la capital de Ecuador?", a: "La capital de Ecuador es Quito." },
    { q: "¿Cuál es la capital de Paraguay?", a: "La capital de Paraguay es Asunción." },
    { q: "¿Cuál es la capital de Uruguay?", a: "La capital de Uruguay es Montevideo." },
    { q: "¿Cuál es la capital de Venezuela?", a: "La capital de Venezuela es Caracas." },
    { q: "¿Cuál es la capital de Cuba?", a: "La capital de Cuba es La Habana." },
    { q: "¿Cuál es la capital de Portugal?", a: "La capital de Portugal es Lisboa." },
    { q: "¿Cuál es la capital de Grecia?", a: "La capital de Grecia es Atenas." },
    { q: "¿Cuál es la capital de Turquía?", a: "La capital de Turquía es Ankara, no Estambul." },
    { q: "¿Cuál es la capital de Corea del Sur?", a: "La capital de Corea del Sur es Seúl." },
    { q: "¿Cuál es el volcán más alto de Chile?", a: "El Ojos del Salado, con 6.893 metros, es el volcán más alto de Chile y del mundo." },
    { q: "¿Cuál es la ciudad más poblada del mundo?", a: "Tokio es la zona metropolitana más poblada del mundo, con más de 37 millones de habitantes." },
    { q: "¿Dónde queda Machu Picchu?", a: "Machu Picchu está en Perú, en la región de Cusco, a 2.430 metros sobre el nivel del mar." },
    { q: "¿Cuál es el continente más grande?", a: "Asia es el continente más grande, con aproximadamente 44,5 millones de km²." },
    { q: "¿Cuál es el continente más pequeño?", a: "Oceanía es el continente más pequeño, con aproximadamente 8,5 millones de km²." },
    { q: "¿Qué países limitan con Chile?", a: "Chile limita con Argentina al este, Bolivia y Perú al norte, y el Océano Pacífico al oeste." },
    { q: "¿Cuántos kilómetros de costa tiene Chile?", a: "Chile tiene aproximadamente 6.435 km de costa continental." },
    { q: "¿Cuál es el país más largo del mundo?", a: "Chile es el país más largo del mundo con aproximadamente 4.270 km de norte a sur." },
    { q: "¿Dónde está la Isla de Pascua?", a: "La Isla de Pascua (Rapa Nui) pertenece a Chile y está en el Océano Pacífico, a unos 3.700 km de la costa." },

    // ═══ HISTORIA (50) ═══
    { q: "¿En qué año llegó Colón a América?", a: "Cristóbal Colón llegó a América el 12 de octubre de 1492." },
    { q: "¿Cuándo fue la independencia de Chile?", a: "Chile declaró su independencia el 12 de febrero de 1818. El 18 de septiembre de 1810 se formó la Primera Junta Nacional." },
    { q: "¿Quién fue el primer presidente de Chile?", a: "Manuel Blanco Encalada fue el primer presidente en 1826. Bernardo O'Higgins fue Director Supremo desde 1817." },
    { q: "¿Quién fue Bernardo O'Higgins?", a: "Bernardo O'Higgins fue el libertador y padre de la patria de Chile. Fue Director Supremo entre 1817 y 1823." },
    { q: "¿Cuándo empezó la Segunda Guerra Mundial?", a: "La Segunda Guerra Mundial comenzó el 1 de septiembre de 1939 y terminó en 1945." },
    { q: "¿Cuándo empezó la Primera Guerra Mundial?", a: "La Primera Guerra Mundial comenzó el 28 de julio de 1914 y terminó el 11 de noviembre de 1918." },
    { q: "¿Quién fue Albert Einstein?", a: "Albert Einstein fue un físico teórico alemán, conocido por la teoría de la relatividad (E=mc²). Nobel de Física en 1921." },
    { q: "¿Quién inventó la electricidad?", a: "La electricidad fue descubierta y desarrollada por varios científicos: Franklin, Faraday, Tesla y Edison fueron figuras clave." },
    { q: "¿Quién inventó el teléfono?", a: "Alexander Graham Bell patentó el teléfono en 1876." },
    { q: "¿Quién inventó Internet?", a: "Internet nació de ARPANET (1969). Tim Berners-Lee creó la World Wide Web en 1989." },
    { q: "¿Cuándo cayó el Muro de Berlín?", a: "El Muro de Berlín cayó el 9 de noviembre de 1989." },
    { q: "¿Quién fue Napoleón Bonaparte?", a: "Napoleón Bonaparte fue un líder militar y emperador de Francia. Gobernó entre 1804 y 1815, conquistando gran parte de Europa." },
    { q: "¿Quién fue Julio César?", a: "Julio César fue un líder político y militar romano. Fue dictador de Roma y fue asesinado en el 44 a.C." },
    { q: "¿Quién fue Cleopatra?", a: "Cleopatra VII fue la última reina del Antiguo Egipto, conocida por su inteligencia política y sus alianzas con Roma." },
    { q: "¿Cuándo se fundó Roma?", a: "Según la tradición, Roma fue fundada el 21 de abril del 753 a.C. por Rómulo y Remo." },
    { q: "¿Qué fue la Revolución Francesa?", a: "La Revolución Francesa (1789-1799) fue un movimiento que derrocó la monarquía absoluta y estableció los principios de libertad, igualdad y fraternidad." },
    { q: "¿Quién fue Simón Bolívar?", a: "Simón Bolívar fue un líder militar y político venezolano que liberó a varios países sudamericanos del dominio español." },
    { q: "¿Quién fue José de San Martín?", a: "José de San Martín fue un militar argentino que lideró la independencia de Argentina, Chile y Perú." },
    { q: "¿Quién fue Arturo Prat?", a: "Arturo Prat fue un oficial naval chileno, héroe del Combate Naval de Iquique (1879) durante la Guerra del Pacífico." },
    { q: "¿Qué fue la Guerra del Pacífico?", a: "La Guerra del Pacífico (1879-1884) enfrentó a Chile contra Bolivia y Perú por el control de territorios ricos en salitre." },
    { q: "¿Cuándo llegó el hombre a la Luna?", a: "Neil Armstrong pisó la Luna el 20 de julio de 1969 durante la misión Apolo 11." },
    { q: "¿Quién fue Mahatma Gandhi?", a: "Mahatma Gandhi fue un líder pacifista indio que lideró el movimiento de independencia de la India mediante la resistencia no violenta." },
    { q: "¿Quién fue Martin Luther King?", a: "Martin Luther King Jr. fue un líder del movimiento por los derechos civiles en EE.UU., famoso por su discurso 'I Have a Dream' (1963)." },
    { q: "¿Quién fue Leonardo da Vinci?", a: "Leonardo da Vinci fue un genio renacentista italiano: pintor, inventor, científico y arquitecto. Pintó la Mona Lisa y La Última Cena." },
    { q: "¿Qué fue el Renacimiento?", a: "El Renacimiento fue un movimiento cultural europeo (siglos XIV-XVII) que impulsó el arte, la ciencia y el pensamiento humanista." },
    { q: "¿Cuándo se abolió la esclavitud en Chile?", a: "Chile abolió la esclavitud en 1823, siendo uno de los primeros países en hacerlo." },
    { q: "¿Qué fue la Revolución Industrial?", a: "La Revolución Industrial (siglos XVIII-XIX) transformó la producción manual en industrial, comenzando en Gran Bretaña." },
    { q: "¿Quién fue Marie Curie?", a: "Marie Curie fue una científica polaca-francesa, primera mujer en ganar un Premio Nobel. Descubrió el polonio y el radio." },
    { q: "¿Quién fue Galileo Galilei?", a: "Galileo Galilei fue un astrónomo italiano considerado el padre de la ciencia moderna. Defendió el modelo heliocéntrico." },
    { q: "¿Qué fue el Imperio Romano?", a: "El Imperio Romano fue una de las civilizaciones más grandes de la historia, abarcando Europa, norte de África y parte de Asia entre el 27 a.C. y el 476 d.C." },
    { q: "¿Cuándo se descubrió la penicilina?", a: "Alexander Fleming descubrió la penicilina en 1928, revolucionando la medicina moderna." },
    { q: "¿Qué fue la Guerra Fría?", a: "La Guerra Fría (1947-1991) fue un período de tensión geopolítica entre Estados Unidos y la Unión Soviética." },
    { q: "¿Cuándo terminó la Unión Soviética?", a: "La Unión Soviética se disolvió oficialmente el 26 de diciembre de 1991." },
    { q: "¿Quién fue Pablo Neruda?", a: "Pablo Neruda fue un poeta chileno, Premio Nobel de Literatura en 1971. Considerado uno de los poetas más importantes del siglo XX." },
    { q: "¿Quién fue Gabriela Mistral?", a: "Gabriela Mistral fue una poeta chilena, primera latinoamericana en ganar el Premio Nobel de Literatura en 1945." },
    { q: "¿Cuándo fue el terremoto de Chile de 1960?", a: "El Gran Terremoto de Valdivia del 22 de mayo de 1960 fue el sismo más fuerte registrado en la historia, con magnitud 9,5." },
    { q: "¿Qué eran los Mayas?", a: "Los Mayas fueron una civilización mesoamericana avanzada, conocida por su escritura, astronomía, matemáticas y arquitectura." },
    { q: "¿Quiénes fueron los Incas?", a: "Los Incas fueron una civilización sudamericana que creó el imperio más grande de América precolombina, con capital en Cusco." },
    { q: "¿Qué fue la Inquisición?", a: "La Inquisición fue una institución de la Iglesia católica dedicada a perseguir la herejía, activa principalmente entre los siglos XII y XVIII." },
    { q: "¿Cuándo se inventó la imprenta?", a: "Johannes Gutenberg inventó la imprenta de tipos móviles alrededor de 1440, revolucionando la difusión del conocimiento." },
    { q: "¿Qué fue el Holocausto?", a: "El Holocausto fue el genocidio perpetrado por la Alemania nazi durante la Segunda Guerra Mundial, donde fueron asesinados aproximadamente 6 millones de judíos." },
    { q: "¿Quién fue Nikola Tesla?", a: "Nikola Tesla fue un inventor serbio-americano, pionero de la corriente alterna (AC) y autor de más de 300 patentes." },
    { q: "¿Quién fue Steve Jobs?", a: "Steve Jobs fue el cofundador de Apple, visionario tecnológico que revolucionó la industria con el Mac, iPhone, iPad y iTunes." },
    { q: "¿Cuándo se creó la ONU?", a: "La Organización de las Naciones Unidas fue fundada el 24 de octubre de 1945, tras la Segunda Guerra Mundial." },
    { q: "¿Qué fue la Batalla de Waterloo?", a: "La Batalla de Waterloo (1815) fue la derrota definitiva de Napoleón Bonaparte, marcando el fin de su imperio." },
    { q: "¿Cuándo empezó la Era Espacial?", a: "La Era Espacial comenzó el 4 de octubre de 1957 con el lanzamiento del Sputnik 1 por la Unión Soviética." },
    { q: "¿Quién fue Fidel Castro?", a: "Fidel Castro fue un revolucionario cubano que lideró la Revolución Cubana de 1959 y gobernó Cuba hasta 2008." },
    { q: "¿Quién fue Nelson Mandela?", a: "Nelson Mandela fue un líder sudafricano contra el apartheid, encarcelado 27 años. Fue el primer presidente negro de Sudáfrica en 1994." },
    { q: "¿Cuándo se inventó el automóvil?", a: "Karl Benz patentó el primer automóvil con motor de combustión interna en 1886." },
    { q: "¿Cuándo se inventó el avión?", a: "Los hermanos Wright realizaron el primer vuelo motorizado exitoso el 17 de diciembre de 1903." }
];

const qnaStr = batch1.map(q =>
    '  { q: ' + JSON.stringify(q.q) + ', a: ' + JSON.stringify(q.a) + ' }'
).join(',\n');

const closingPattern = '\n];\n';
const lastClose = content.lastIndexOf(closingPattern);
const before = content.substring(0, lastClose);
const after = content.substring(lastClose);

const injected = before + ',\n\n  // ══════════════════════════════════════════════\n  // MATEMÁTICAS (50) + GEOGRAFÍA (50) + HISTORIA (50)\n  // ══════════════════════════════════════════════\n' + qnaStr + after;

fs.writeFileSync(filePath, injected, 'utf8');
const final = fs.readFileSync(filePath, 'utf8');
const count = (final.match(/\{ q: /g) || []).length;
console.log('✅ Batch 1 done: ' + count + ' Q&As | +' + batch1.length + ' added');
