const fs = require('fs');
const path = require('path');
const filePath = path.resolve('v3/js/chatbot.js');
let content = fs.readFileSync(filePath, 'utf8');

const batch3 = [
    // ═══ CHILE Y ACTUALIDAD (50) ═══
    { q: "¿Cuál es la moneda de Chile?", a: "El Peso Chileno (CLP)." },
    { q: "¿Cuántos habitantes tiene Chile?", a: "Aproximadamente 19-20 millones." },
    { q: "¿Cuál es el idioma oficial de Chile?", a: "El español (castellano)." },
    { q: "¿Qué es el SII?", a: "El Servicio de Impuestos Internos, encargado de la administración tributaria en Chile." },
    { q: "¿Qué es una boleta electrónica?", a: "Un documento tributario digital que reemplaza a la boleta de papel en Chile." },
    { q: "¿Qué es el IVA?", a: "El Impuesto al Valor Agregado. En Chile es del 19%." },
    { q: "¿Cuántas regiones tiene Chile?", a: "Chile tiene 16 regiones administrativas." },
    { q: "¿Cuál es el desierto más árido del mundo?", a: "El Desierto de Atacama, en el norte de Chile." },
    { q: "¿Cuál es el río más largo de Chile?", a: "El río Loa, con aproximadamente 440 km." },
    { q: "¿Cuál es la ciudad más grande de Chile?", a: "Santiago, con una población metropolitana de más de 7 millones." },
    { q: "¿Qué es CORFO?", a: "La Corporación de Fomento de la Producción, que apoya el emprendimiento en Chile." },
    { q: "¿Qué es SERCOTEC?", a: "El Servicio de Cooperación Técnica, que apoya a micro y pequeñas empresas en Chile." },
    { q: "¿Qué es Startup Chile?", a: "Un programa de CORFO que ofrece financiamiento y apoyo a startups." },
    { q: "¿Cuál es el código telefónico de Chile?", a: "El código de país es +56." },
    { q: "¿Cuál es la zona horaria de Chile?", a: "Chile continental usa UTC-3 en verano y UTC-4 en invierno." },
    { q: "¿Qué se celebra el 18 de septiembre?", a: "Las Fiestas Patrias de Chile, conmemorando la Primera Junta Nacional de Gobierno de 1810." },
    { q: "¿Qué se celebra el 21 de mayo?", a: "El Día de las Glorias Navales, en honor al Combate Naval de Iquique." },
    { q: "¿Qué es el Banco Central de Chile?", a: "La institución autónoma que regula la política monetaria y financiera del país." },
    { q: "¿Qué es la CMF?", a: "La Comisión para el Mercado Financiero, que supervisa y regula el sistema financiero chileno." },
    { q: "¿Cuál es la temperatura promedio de Santiago?", a: "Santiago tiene clima mediterráneo con promedio de 14°C anual. Veranos de 30°C e inviernos de 3°C." },
    { q: "¿Cuáles son los principales productos de exportación de Chile?", a: "Cobre, litio, frutas, salmón, vino y productos forestales." },
    { q: "¿Qué porcentaje de cobre mundial produce Chile?", a: "Chile produce alrededor del 25-28% del cobre mundial." },
    { q: "¿Qué es la Bolsa de Santiago?", a: "La principal bolsa de valores de Chile donde se transan acciones e instrumentos financieros." },
    { q: "¿Qué es el Metro de Santiago?", a: "El sistema de transporte masivo subterráneo de Santiago, con 7 líneas y más de 130 estaciones." },
    { q: "¿Cuántos aeropuertos tiene Chile?", a: "Chile tiene más de 30 aeropuertos, siendo el principal el Aeropuerto Internacional Arturo Merino Benítez (SCL)." },
    { q: "¿Qué es la Patagonia chilena?", a: "La región sur de Chile, conocida por glaciares, fiordos y paisajes de naturaleza prístina." },
    { q: "¿Cuál es el volcán activo más alto de Chile?", a: "El volcán Láscar, en la Región de Antofagasta, a 5.592 metros." },
    { q: "¿Cuántos volcanes activos tiene Chile?", a: "Chile tiene aproximadamente 90 volcanes activos, la segunda mayor cantidad del mundo." },
    { q: "¿Qué es el pisco chileno?", a: "Un destilado de uva producido en las regiones de Atacama y Coquimbo, con denominación de origen." },
    { q: "¿Quién es Violeta Parra?", a: "Cantautora, artista y folclorista chilena, autora de 'Gracias a la Vida'. Figura central de la cultura chilena." },
    { q: "¿Quién es Víctor Jara?", a: "Cantautor y director teatral chileno, ícono de la Nueva Canción Chilena." },
    { q: "¿Cuáles son los principales puertos de Chile?", a: "Valparaíso, San Antonio, Arica, Iquique y San Vicente." },
    { q: "¿Qué es la Teletón?", a: "Una campaña solidaria chilena que recauda fondos para la rehabilitación de niños con discapacidad." },
    { q: "¿Cuál es el sueldo mínimo en Chile?", a: "El sueldo mínimo en Chile se actualiza periódicamente. Consulta fuentes oficiales para la cifra vigente." },
    { q: "¿Qué es un RUT?", a: "El Rol Único Tributario, número de identificación fiscal en Chile." },
    { q: "¿Qué es la AFP?", a: "Administradora de Fondos de Pensiones, el sistema privado de pensiones en Chile." },
    { q: "¿Qué es una Isapre?", a: "Instituciones de Salud Previsional, aseguradoras de salud privadas en Chile." },
    { q: "¿Qué es Fonasa?", a: "El Fondo Nacional de Salud, sistema público de salud en Chile." },
    { q: "¿Cuáles son las universidades más importantes de Chile?", a: "Universidad de Chile, PUC, Universidad de Concepción, USM, entre otras." },
    { q: "¿Chile tiene premio Nobel?", a: "Sí, dos en Literatura: Gabriela Mistral (1945) y Pablo Neruda (1971)." },
    { q: "¿Cuántos mundiales de fútbol ha ganado Chile?", a: "Chile no ha ganado un mundial de fútbol. Su mejor resultado fue 3er lugar en 1962 como local." },
    { q: "¿Qué es una DTE?", a: "Documento Tributario Electrónico: facturas, boletas y otros documentos fiscales en formato digital." },
    { q: "¿Cuál es el PIB de Chile?", a: "El PIB de Chile ronda los 300-330 mil millones de dólares (varía anualmente). Es una de las economías más estables de Latinoamérica." },
    { q: "¿Qué es el litio?", a: "Un metal ligero esencial para baterías. Chile tiene las mayores reservas del mundo en el Salar de Atacama." },
    { q: "¿Qué es una zona franca?", a: "Un área geográfica con beneficios tributarios y aduaneros. En Chile, la más conocida es la de Iquique (ZOFRI)." },
    { q: "¿Cuántas horas tiene la jornada laboral en Chile?", a: "45 horas semanales (en proceso de reducción a 40 horas)." },
    { q: "¿Qué es el finiquito?", a: "Documento legal que pone fin a la relación laboral entre empleador y trabajador en Chile." },
    { q: "¿Qué se necesita para crear una empresa en Chile?", a: "Se puede crear online en tuempresaenundia.cl. Se necesita RUT, dirección, capital y definir tipo de sociedad." },
    { q: "¿Qué es el CAE?", a: "Crédito con Aval del Estado, un sistema de financiamiento para educación superior en Chile." },

    // ═══ NEGOCIOS (50) ═══
    { q: "¿Qué es una SpA?", a: "Sociedad por Acciones: tipo de sociedad flexible en Chile, muy usada por startups." },
    { q: "¿Qué es una EIRL?", a: "Empresa Individual de Responsabilidad Limitada: empresa unipersonal con responsabilidad limitada." },
    { q: "¿Qué es el ROI?", a: "Return on Investment: rentabilidad de una inversión. (Ganancia - Inversión) / Inversión × 100%." },
    { q: "¿Qué es un MVP?", a: "Minimum Viable Product: versión mínima de un producto para validar una idea de negocio." },
    { q: "¿Qué es outsourcing?", a: "Contratar servicios externos para funciones que podrían hacerse internamente." },
    { q: "¿Qué es scrum?", a: "Marco de trabajo ágil que organiza proyectos en sprints con roles definidos." },
    { q: "¿Qué es DevOps?", a: "Cultura que integra desarrollo y operaciones para acelerar entregas de software." },
    { q: "¿Qué es la transformación digital?", a: "Integración de tecnología en todas las áreas del negocio para mejorar operaciones y crear valor." },
    { q: "¿Qué es un pitch?", a: "Una presentación breve y persuasiva de un proyecto o negocio ante potenciales inversores o clientes." },
    { q: "¿Qué es un KPI?", a: "Key Performance Indicator: métrica clave para medir el rendimiento de un proceso o estrategia." },
    { q: "¿Qué es un stakeholder?", a: "Cualquier persona o grupo que tiene interés o se ve afectado por un proyecto o empresa." },
    { q: "¿Qué es el flujo de caja?", a: "El movimiento de dinero que entra y sale de una empresa en un periodo determinado." },
    { q: "¿Qué es un balance general?", a: "Un estado financiero que muestra activos, pasivos y patrimonio de una empresa en un momento dado." },
    { q: "¿Qué es el EBITDA?", a: "Earnings Before Interest, Taxes, Depreciation and Amortization: indicador de rentabilidad operativa." },
    { q: "¿Qué es una startup?", a: "Una empresa emergente con alto potencial de crecimiento, generalmente basada en innovación tecnológica." },
    { q: "¿Qué es venture capital?", a: "Capital de riesgo: inversión en empresas emergentes con alto potencial a cambio de participación accionaria." },
    { q: "¿Qué es bootstrapping?", a: "Financiar una empresa con recursos propios, sin inversores externos." },
    { q: "¿Qué es una ronda de inversión?", a: "Proceso donde una startup busca financiamiento externo (Seed, Serie A, B, C…)." },
    { q: "¿Qué es el break-even?", a: "El punto de equilibrio donde los ingresos igualan los costos. A partir de ahí, hay ganancia." },
    { q: "¿Qué es un modelo de negocio?", a: "El esquema que define cómo una empresa crea, entrega y captura valor económico." },
    { q: "¿Qué es el modelo canvas?", a: "El Business Model Canvas: herramienta visual de 9 bloques para diseñar modelos de negocio." },
    { q: "¿Qué es B2B?", a: "Business to Business: empresas que venden productos o servicios a otras empresas." },
    { q: "¿Qué es B2C?", a: "Business to Consumer: empresas que venden directamente al consumidor final." },
    { q: "¿Qué es un lead?", a: "Un contacto potencial interesado en tus productos o servicios." },
    { q: "¿Qué es un funnel de ventas?", a: "El embudo que representa las etapas del proceso de venta: desde prospecto hasta cliente." },
    { q: "¿Qué es el churn rate?", a: "La tasa de cancelación de clientes en un periodo determinado." },
    { q: "¿Qué es una SaaS company?", a: "Una empresa que vende software como servicio por suscripción." },
    { q: "¿Qué es el product-market fit?", a: "El momento donde un producto satisface una demanda real del mercado." },
    { q: "¿Qué es el growth hacking?", a: "Estrategias creativas de bajo costo para adquirir y retener usuarios rápidamente." },
    { q: "¿Qué es un NDA?", a: "Non-Disclosure Agreement: acuerdo de confidencialidad entre partes." },
    { q: "¿Qué es due diligence?", a: "Proceso de investigación exhaustiva antes de una inversión o transacción empresarial." },
    { q: "¿Qué es un term sheet?", a: "Documento no vinculante que establece los términos básicos de una inversión." },
    { q: "¿Qué es el equity?", a: "La participación accionaria o el valor patrimonial de una empresa." },
    { q: "¿Qué es un board of directors?", a: "El directorio: grupo de personas elegidas para supervisar y dirigir una empresa." },
    { q: "¿Qué es la escalabilidad?", a: "La capacidad de un negocio o sistema para crecer sin que los costos aumenten proporcionalmente." },
    { q: "¿Qué es el time to market?", a: "El tiempo que tarda un producto desde su concepción hasta estar disponible para los clientes." },
    { q: "¿Qué es un roadmap?", a: "Un plan estratégico visual que define hitos y objetivos de un producto o proyecto a lo largo del tiempo." },
    { q: "¿Qué es OKR?", a: "Objectives and Key Results: metodología de gestión para definir y medir objetivos." },
    { q: "¿Qué es lean startup?", a: "Metodología que busca crear negocios reduciendo ciclos de desarrollo y validando hipótesis rápidamente." },
    { q: "¿Qué es design thinking?", a: "Metodología de innovación centrada en el usuario para resolver problemas complejos." },
    { q: "¿Qué es customer success?", a: "Estrategia empresarial enfocada en asegurar que los clientes logren sus objetivos con tu producto." },
    { q: "¿Qué es el LTV?", a: "Lifetime Value: el valor total que un cliente genera durante toda su relación con la empresa." },
    { q: "¿Qué es el CAC?", a: "Customer Acquisition Cost: el costo promedio de adquirir un nuevo cliente." },
    { q: "¿Qué es una propuesta de valor?", a: "La razón principal por la que un cliente debería elegir tu producto o servicio sobre la competencia." },
    { q: "¿Qué es benchmarking?", a: "Comparar las prácticas y resultados de tu empresa con las mejores del mercado." },
    { q: "¿Qué es un pivot?", a: "Un cambio estratégico fundamental en el modelo de negocio de una startup." },
    { q: "¿Qué es el burn rate?", a: "La velocidad a la que una empresa gasta su capital antes de generar ingresos positivos." },
    { q: "¿Qué es un unicornio?", a: "Una startup valorada en más de 1.000 millones de dólares." },
    { q: "¿Qué es una SLA?", a: "Service Level Agreement: contrato que define niveles de servicio garantizados." },
    { q: "¿Qué es compliance?", a: "El cumplimiento normativo: asegurar que la empresa opera dentro del marco legal y regulatorio." },

    // ═══ CURIOSIDADES (50) ═══
    { q: "¿Cuál es el animal más rápido del mundo?", a: "El guepardo en tierra (120 km/h). El halcón peregrino en aire (+300 km/h en picada)." },
    { q: "¿Cuál es el animal más grande del mundo?", a: "La ballena azul: hasta 30 metros y 150+ toneladas." },
    { q: "¿Cuál es el animal más pequeño del mundo?", a: "La rana Paedophryne amauensis de Papúa Nueva Guinea, con apenas 7,7 mm." },
    { q: "¿Cuántos años vive una tortuga?", a: "Algunas tortugas gigantes pueden vivir más de 150-200 años." },
    { q: "¿Cuál es el edificio más alto del mundo?", a: "El Burj Khalifa en Dubái, con 828 metros de altura." },
    { q: "¿Cuál es el puente más largo del mundo?", a: "El puente Danyang-Kunshan en China, con 164,8 km." },
    { q: "¿Cuántas especies existen en la Tierra?", a: "Se estima que hay entre 8 y 10 millones de especies, de las cuales solo 1,5 millones están catalogadas." },
    { q: "¿Cuánto pesa el Sol?", a: "Aproximadamente 1,989 × 10³⁰ kg, unas 333.000 veces la masa de la Tierra." },
    { q: "¿A qué distancia está el Sol de la Tierra?", a: "Aproximadamente 150 millones de km (1 unidad astronómica)." },
    { q: "¿A qué distancia está la Luna?", a: "Aproximadamente 384.400 km de la Tierra." },
    { q: "¿Cuánto tarda la luz del Sol en llegar a la Tierra?", a: "Aproximadamente 8 minutos y 20 segundos." },
    { q: "¿Cuál es el metal más caro del mundo?", a: "El rodio, que puede superar los 500 dólares por gramo." },
    { q: "¿Cuál es el país con más islas?", a: "Suecia, con más de 267.000 islas." },
    { q: "¿Cuántas personas han pisado la Luna?", a: "12 astronautas han caminado sobre la Luna, todos del programa Apolo de la NASA." },
    { q: "¿Qué porcentaje de la Tierra es agua?", a: "Aproximadamente el 71% de la superficie terrestre está cubierta de agua." },
    { q: "¿Cuánta agua dulce hay en la Tierra?", a: "Solo el 2,5% del agua total es dulce, y la mayoría está en glaciares." },
    { q: "¿Cuál es la profundidad máxima del océano?", a: "La Fosa de las Marianas tiene 10.994 metros de profundidad." },
    { q: "¿Cuántos dedos tiene un pulpo?", a: "Un pulpo tiene 8 tentáculos (brazo), no dedos. 3 corazones y sangre azul." },
    { q: "¿El tomate es fruta o verdura?", a: "Botánicamente es una fruta (una baya), pero culinariamente se trata como verdura." },
    { q: "¿El plátano es una hierba?", a: "Técnicamente sí: la planta del banano es una hierba gigante, no un árbol." },
    { q: "¿Cuántos litros de sangre bombea el corazón al día?", a: "Aproximadamente 7.500 litros por día." },
    { q: "¿Cuántas veces late el corazón por minuto?", a: "En reposo, entre 60 y 100 latidos por minuto." },
    { q: "¿Cuántos km de vasos sanguíneos tiene el cuerpo?", a: "Aproximadamente 100.000 km, suficiente para dar más de 2 vueltas a la Tierra." },
    { q: "¿Cuántas veces parpadea una persona al día?", a: "Aproximadamente 15.000 a 20.000 veces al día." },
    { q: "¿Es cierto que los tiburones no tienen huesos?", a: "Sí, su esqueleto es de cartílago, no de hueso." },
    { q: "¿Los delfines duermen?", a: "Sí, pero con medio cerebro a la vez para seguir respirando en la superficie." },
    { q: "¿Cuántos años puede vivir un loro?", a: "Algunas especies de loros pueden vivir 50-80 años." },
    { q: "¿Cuál es el instrumento más antiguo?", a: "Se han encontrado flautas de hueso de más de 40.000 años de antigüedad." },
    { q: "¿Cuántas lenguas habla la persona más políglota?", a: "Se han documentado personas que hablan más de 40 idiomas." },
    { q: "¿Qué es un palíndromo?", a: "Una palabra o frase que se lee igual de izquierda a derecha. Ejemplo: 'reconocer'." },
    { q: "¿Cuál es la palabra más larga del español?", a: "'Electroencefalografista', con 23 letras." },
    { q: "¿Cuántos megapíxeles tiene el ojo humano?", a: "Se estima que equivale a unos 576 megapíxeles." },
    { q: "¿Cuántas estrellas se ven a simple vista?", a: "En condiciones ideales, cerca de 5.000 estrellas." },
    { q: "¿Qué tan caliente es el centro de la Tierra?", a: "El núcleo interno alcanza unos 5.500°C, similar a la superficie del Sol." },
    { q: "¿Cuánto tarda la Tierra en rotar sobre su eje?", a: "23 horas, 56 minutos y 4 segundos (un día sideral)." },
    { q: "¿Cuál es el organismo más antiguo de la Tierra?", a: "Árboles como el pino Bristlecone pueden vivir más de 5.000 años." },
    { q: "¿La Gran Muralla China se ve desde el espacio?", a: "Contrario al mito popular, no es visible a simple vista desde el espacio." },
    { q: "¿Cuántos libros se publican al año en el mundo?", a: "Se estima que más de 2,2 millones de títulos nuevos por año." },
    { q: "¿Quién inventó el chocolate?", a: "Los Mayas y Aztecas consumían cacao hace más de 3.000 años. El chocolate moderno se desarrolló en Europa." },
    { q: "¿Cuánto café se consume en el mundo?", a: "Más de 2.250 millones de tazas diarias." },
    { q: "¿Cuál es el libro más vendido de la historia?", a: "La Biblia, con más de 5.000 millones de copias estimadas." },
    { q: "¿Cuántos píxeles tiene una pantalla 4K?", a: "3.840 × 2.160 = 8.294.400 píxeles (aproximadamente 8,3 megapíxeles)." },
    { q: "¿Cuántas canciones tiene Spotify?", a: "Más de 100 millones de canciones disponibles." },
    { q: "¿Cuál es el videojuego más vendido de todos los tiempos?", a: "Minecraft, con más de 300 millones de copias vendidas." },
    { q: "¿Cuántos correos electrónicos se envían al día?", a: "Aproximadamente 333.000 millones de correos electrónicos diarios." },
    { q: "¿Cuántos sitios web hay en internet?", a: "Más de 1.900 millones de sitios web registrados." },
    { q: "¿Cuántos usuarios tiene internet?", a: "Más de 5.400 millones de personas usan internet actualmente." },
    { q: "¿Cuántos smartphones hay en el mundo?", a: "Más de 6.800 millones de smartphones activos." },
    { q: "¿Cuál es el país más feliz del mundo?", a: "Finlandia ha liderado el ranking de felicidad mundial en los últimos años." },
    { q: "¿Cuánto dura un rayo?", a: "Un rayo dura menos de un segundo, pero puede calentar el aire a 30.000°C." }
];

const qnaStr = batch3.map(q =>
    '  { q: ' + JSON.stringify(q.q) + ', a: ' + JSON.stringify(q.a) + ' }'
).join(',\n');

const closingPattern = '\n];\n';
const lastClose = content.lastIndexOf(closingPattern);
const before = content.substring(0, lastClose);
const after = content.substring(lastClose);

const injected = before + ',\n\n  // ══════════════════════════════════════════════\n  // CHILE (50) + NEGOCIOS (50) + CURIOSIDADES (50)\n  // ══════════════════════════════════════════════\n' + qnaStr + after;

fs.writeFileSync(filePath, injected, 'utf8');
const final = fs.readFileSync(filePath, 'utf8');
const count = (final.match(/\{ q: /g) || []).length;
console.log('✅ Batch 3 done: ' + count + ' Q&As TOTAL');
console.log('   File size: ' + (final.length / 1024).toFixed(1) + 'KB');
